[tool.isort]
profile = "black"
multi_line_output = 3


# https://flakehell.readthedocs.io/config.html
[tool.flakehell]

# Inherit from baseline configuration
base = [
    "https://raw.githubusercontent.com/life4/flakehell/master/pyproject.toml",
    #".flakehell.toml",
]

# Make output beautiful
format='colored'

# 80 chars limit isn't enough in 21 century
max_line_length = 120

# show line of source code in output
show_source = false


[tool.flakehell.plugins]
pycodestyle = ["+*", "-E203", "-W503", "-W504"]
pyflakes = ["+*"]
flake8-black = ["+*"]
flake8-isort = ["+*"]
#flake8-bandit = ["+*"]
#flake8-bugbear = ["+*"]


[tool.flakehell.exceptions."tsdg/util/tictrack/README.md"]
pycodestyle = ["-E111", "-E114"]
pyflakes = ["-F821"]
