[tool.isort]
profile = "black"
multi_line_output = 3


# https://flakehell.readthedocs.io/config.html
[tool.flakehell]

# Inherit from baseline configuration
base = [
    "https://raw.githubusercontent.com/life4/flakehell/master/pyproject.toml",
    #".flakehell.toml",
]

# Make output beautiful
format='colored'

# 80 chars limit isn't enough in 21 century
max_line_length = 120

# show line of source code in output
show_source = false


[tool.flakehell.plugins]
pycodestyle = ["+*", "-E203", "-W503", "-W504"]
pyflakes = ["+*"]
flake8-black = ["+*"]
flake8-isort = ["+*"]
flake8-bandit = ["+*"]
flake8-bugbear = ["+*"]


[tool.flakehell.exceptions."**/README.md"]
pycodestyle = ["-E111", "-E114"]
pyflakes = ["-F821"]
flake8-black = ["-BLK901"]
flake8-isort = ["-I003"]
flake8-bugbear = ["-B007"]

[tool.flakehell.exceptions."tests"]
flake8-bandit = ["-S101", "-S105", "-S106"]

[tool.flakehell.exceptions."tsperf/adapter/__init__.py"]
pyflakes = ["-F401"]

[tool.flakehell.exceptions."tsperf/adapter"]
flake8-bandit = ["-S608"]

[tool.flakehell.exceptions."tsperf/util/float_simulator/__init__.py"]
flake8-bandit = ["-S311"]


[tool.pytest.ini_options]
minversion = "2.0"
addopts = """
  -rfsEX -p pytester --strict-markers --verbosity=3
  --cov --cov-report=term-missing --cov-report=xml
  --capture=no
  """
log_level = "DEBUG"
log_cli_level = "DEBUG"
testpaths = ["tests"]
xfail_strict = true
markers = [
]

[tool.coverage.run]
branch = false
source = ["tsdg", "tsperf", "tsqt"]
omit = [
    "tests/*",
    "tsperf/write/cli.py",
    "tsperf/read/cli.py",
]

[tool.coverage.report]
fail_under = 0
show_missing = true
omit = [
    "tests/*",
    "tsperf/write/cli.py",
    "tsperf/read/cli.py",
]
