# example docker-compose when inserting 1000 values for 1000 channels into CrateDB using the temperature schema
# prometheus metrics for ID 1 - 500 on port 8000, for ID 501 - 1000 on port 8001
# assuming TimescaleDB runs on localhost and an existing TimescaleDB Table named tsperf.
# Username and Password have to be inserted before running
version: "2.3"
services:

  datagen1:
    image: tsperf
    command: [ "tsperf", "write" ]
    ports:
      - 8000:8000
    environment:
      ID_START: 1
      ID_END: 500
      INGEST_MODE: 1
      INGEST_SIZE: 1000
      ADAPTER: timescaledb
      ADDRESS: "host.docker.internal:5432"
      USERNAME: ""
      PASSWORD: ""
      DATABASE: "tsperf"
      TABLE: "timeseries"
      SCHEMA: "tsperf.schema.basic:environment.json"

  datagen2:
    image: tsperf
    command: [ "tsperf", "write" ]
    ports:
      - 8001:8000
    environment:
      ID_START: 501
      ID_END: 1000
      INGEST_MODE: 1
      INGEST_SIZE: 1000
      ADAPTER: timescaledb
      ADDRESS: "host.docker.internal:5432"
      USERNAME: ""
      PASSWORD: ""
      DATABASE: "tsperf"
      TABLE: "timeseries"
      SCHEMA: "tsperf.schema.basic:environment.json"
