# example docker-compose when inserting 1000 values for 1000 channels into InfluxDB using the temperature schema
# prometheus metrics for ID 1 - 500 on port 8000, for ID 501 - 1000 on port 8001
# assuming InfluxDB runs on localhost
# Token and Organization have to be inserted before running
version: "2.3"
services:

  datagen1:
    image: tsperf
    command: [ "tsperf", "write" ]
    ports:
      - 8000:8000
    environment:
      ID_START: 1
      ID_END: 500
      ADDRESS: "host.docker.internal:8086"
      INFLUXDB_ORGANIZATION: ""
      INFLUXDB_TOKEN: ""
      INGEST_MODE: 1
      INGEST_SIZE: 1000
      SCHEMA: "tsperf.schema.basic:environment.json"
      ADAPTER: influxdb

  datagen2:
    image: tsperf
    command: [ "tsperf", "write" ]
    ports:
      - 8001:8000
    environment:
      ID_START: 501
      ID_END: 1000
      ADDRESS: "host.docker.internal:8086"
      INFLUXDB_ORGANIZATION: ""
      INFLUXDB_TOKEN: ""
      INGEST_MODE: 1
      INGEST_SIZE: 1000
      SCHEMA: "tsperf.schema.basic:environment.json"
      ADAPTER: influxdb
