version: "2.3"
services:

  datagen:
    image: tsperf
    command: [ "tsperf", "write" ]
    ports:
      - 8000:8000

    environment:
      ID_START: 1
      ID_END: 100

      INGEST_MODE: consecutive
      INGEST_SIZE: 720
      TIMESTAMP_DELTA: 5

      ADAPTER: cratedb
      ADDRESS: "host.docker.internal:4200"
      # USERNAME: ""
      # PASSWORD: ""
      SCHEMA: "tsperf.schema.factory.simple:machine.json"
