on:
  pull_request:
    branches:
      - master
    paths:
      - 'data_generator/**'
      - 'query_timer/**'
      - 'tests/**'

name: code_quality

jobs:
    static_code_analysis:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e .
            pip install -e ."[testing]"
        - name: Lint with flake8
          run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 ./data_generator/ --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 ./query_timer/ --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings.
            flake8 ./data_generator/ --count --exit-zero --max-complexity=7 --max-line-length=127 --statistics
            flake8 ./query_timer/ --count --exit-zero --max-complexity=7 --max-line-length=127 --statistics
    unit_tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e .
            pip install -e ."[testing]"
        - name: Test with pytest
          run: |
            pytest ./tests/
    code_coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e .
            pip install -e ."[testing]"
        - name: Measure code coverage
          run: |
            pytest --cov=./data_generator --cov=./query_timer --cov-fail-under=95 --cov-branch --cov-report term ./tests
