on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'

name: code_quality

jobs:
    static_code_analysis:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r src/test/requirements.txt
        - name: Lint with flake8
          run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 ./src/ --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings.
            flake8 ./src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    unit_tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r src/test/requirements.txt
        - name: Test with pytest
          run: |
            pytest ./src/test/
    code_coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r src/test/requirements.txt
        - name: Measure code coverage
          run: |
            percentage=$(pytest --cov=./src/modules/ --cov-report term ./src/test | grep -E '[TOTAL]' | awk '{print $4}' | tr -d % )
            if [ -z "$percentage" ];then
              echo "pytest failed, no code coverage result"
              exit -1;
            fi;
            if (("$percentage" < 95));then
              echo "Coverage failed because percentage is lower than 95%: $percentage%"
              exit -1;
            fi;