name: Tests

on:
  pull_request:
    branches:
      - master
    paths:
      - 'data_generator/**'
      - 'query_timer/**'
      - 'tests/**'

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Lint with flake8
          run: make lint
    tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Test with pytest
          run: make test
    coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Measure code coverage
          run: make coverage
